name: dashkiosk-browser
version: '0.1'
summary: Chromium in Kiosk mode specifically adjusted for dashkiosk
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: strict

apps:
  dashkiosk-browser:
    command: desktop-launch xwayland-dashkiosk-launch chromium.launcher
    daemon: simple
    desktop: usr/share/applications/chromium-browser.desktop
    environment:
      CHROME_DESKTOP: chromium.desktop
      XWAYLAND_I3_CONFIG_FILE: $SNAP/i3.config
    slots: [ x11 ]
    plugs:
      - avahi-observe
      - browser-sandbox
      - hardware-observe
      - home
      - mount-observe
      - network
      - network-bind
      - network-manager
      - opengl
      - password-manager-service
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - wayland
      - x11-plug

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  x11-plug:
    interface: x11

parts:
  chromium:
    source: .
    plugin: nil
    stage-packages:
      - chromium-browser
      - chromium-codecs-ffmpeg-extra
      - avahi-utils
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av chromium.launcher $SNAPCRAFT_PART_INSTALL/bin/
      cp -av xwayland-dashkiosk-launch $SNAPCRAFT_PART_INSTALL/bin/
      cp -av i3.config $SNAPCRAFT_PART_INSTALL/
    after: [desktop-gtk3, xwayland-kiosk-helper]
